workflow:
  continue_runs:
    type: checkbox
    default: false
    description: Flag to continue previously computated runs. If False existing ms_data
      will be deleted.
  create_database:
    type: checkbox
    default: true
    description: Flag to create a database.
  import_raw_data:
    type: checkbox
    default: true
    description: Flag to import the raw data.
  find_features:
    type: checkbox
    default: true
    description: Flag to perform feature finding.
  search_data:
    type: checkbox
    default: true
    description: Flag to perform search.
  recalibrate_data:
    type: checkbox
    default: true
    description: Flag to perform recalibration.
  align:
    type: checkbox
    default: false
    description: Flag to align the data.
  match:
    type: checkbox
    default: false
    description: Flag to perform match-between runs.
  lfq_quantification:
    type: checkbox
    default: true
    description: Flag to perfrom lfq normalization.
general:
  n_processes:
    type: spinbox
    min: 1
    max: 60
    default: 60
    description: Maximum number of processes for multiprocessing. If larger than number
      of processors it will be capped.
experiment:
  results_path:
    type: path
    default: null
    filetype:
    - hdf
    folder: false
    description: Path where the results should be stored.
  shortnames:
    type: list
    default: []
    description: List of shortnames for the raw files.
  file_paths:
    type: list
    default: []
    description: Filepaths of the experiments.
  fractions:
    type: list
    default: []
    description: List of fractions for the raw files.
  matching_groups:
    type: list
    default: []
    description: List of macthing groups for the raw files. This only allows match-between-runs
      of files within the same groups.
  database_path:
    type: path
    default: null
    filetype:
    - hdf
    folder: false
    description: Path to library file (.hdf).
  fasta_paths:
    type: list
    default: []
    description: List of paths for FASTA files.
raw:
  n_most_abundant:
    type: spinbox
    min: 1
    max: 1000
    default: 400
    description: Number of most abundant peaks to be isolated from raw spectra.
  use_profile_ms1:
    type: checkbox
    default: false
    description: Use profile data for MS1 and perform own centroiding.
fasta:
  mods_fixed:
    type: checkgroup
    value:
      cC: carbamidomethylation of C
      oxM: oxidation of M
      aK: acetylation of lysine
      pS: phosphorylation of S
      pT: phosphorylation of T
      pY: phosphorylation of Y
      deamN: deamidation of N
      deamQ: deamidation of Q
      tmt0K: TMT zero on K
      tmt0Y: TMT zero on Y
      tmt2K: TMT duplex on K
      tmt2Y: TMT duplex on Y
      tmt6K: TMT sixplex/tenplex on K
      tmt6Y: TMT sixplex/tenplex on Y
      itraq4K: iTRAQ 4-plex on K
      itraq4Y: iTRAQ 4-plex on Y
      itraq8K: iTRAQ 8-plex on K
      itraq8Y: iTRAQ 8-plex on Y
      eK: EASItag 6-plex on K
    default:
    - cC
    description: Fixed modifications.
  mods_fixed_terminal:
    type: checkgroup
    value:
      cm<C: pyro-cmC
      pg<E: pyro-E
      pg<Q: pyro-Q
      tmt0<^: TMT zero on peptide N-terminus
      tmt2<^: TMT duplex on peptide N-terminus
      tmt6<^: TMT sixplex/tenplex on peptide N-terminus
      itraq4K<^: iTRAQ 4-plex on peptide N-terminus
      itraq8K<^: iTRAQ 8-plex on peptide N-terminus
      e<^: EASItag 6-plex on peptide N-terminus
      arg10>R: Arg 10 on peptide C-terminus
      arg6>R: Arg 6 on peptide C-terminus
      lys8>K: Lys 8 on peptide C-terminus
    default: []
    description: Fixed terminal modifications.
  mods_variable:
    type: checkgroup
    value:
      cC: carbamidomethylation of C
      oxM: oxidation of M
      aK: acetylation of lysine
      pS: phosphorylation of S
      pT: phosphorylation of T
      pY: phosphorylation of Y
      deamN: deamidation of N
      deamQ: deamidation of Q
      tmt0K: TMT zero on K
      tmt0Y: TMT zero on Y
      tmt2K: TMT duplex on K
      tmt2Y: TMT duplex on Y
      tmt6K: TMT sixplex/tenplex on K
      tmt6Y: TMT sixplex/tenplex on Y
      itraq4K: iTRAQ 4-plex on K
      itraq4Y: iTRAQ 4-plex on Y
      itraq8K: iTRAQ 8-plex on K
      itraq8Y: iTRAQ 8-plex on Y
      eK: EASItag 6-plex on K
    default:
    - oxM
    description: Variable modifications.
  mods_variable_terminal:
    type: checkgroup
    value:
      cm<C: pyro-cmC
      pg<E: pyro-E
      pg<Q: pyro-Q
      tmt0<^: TMT zero on peptide N-terminus
      tmt2<^: TMT duplex on peptide N-terminus
      tmt6<^: TMT sixplex/tenplex on peptide N-terminus
      itraq4K<^: iTRAQ 4-plex on peptide N-terminus
      itraq8K<^: iTRAQ 8-plex on peptide N-terminus
      e<^: EASItag 6-plex on peptide N-terminus
      arg10>R: Arg 10 on peptide C-terminus
      arg6>R: Arg 6 on peptide C-terminus
      lys8>K: Lys 8 on peptide C-terminus
    default: []
    description: Varibale terminal modifications.
  mods_fixed_terminal_prot:
    type: checkgroup
    value:
      a<^: acetylation of protein N-terminus
      am>^: amidation of protein C-terminus
    default: []
    description: Fixed terminal modifications on proteins.
  mods_variable_terminal_prot:
    type: checkgroup
    value:
      a<^: acetylation of protein N-terminus
      am>^: amidation of protein C-terminus
    default:
    - a<^
    description: Varibale terminal modifications on proteins.
  n_missed_cleavages:
    type: spinbox
    min: 0
    max: 99
    default: 2
    description: Number of missed cleavages.
  pep_length_min:
    type: spinbox
    min: 7
    max: 99
    default: 7
    description: Minimum peptide length.
  pep_length_max:
    type: spinbox
    min: 7
    max: 99
    default: 27
    description: Maximum peptide length.
  isoforms_max:
    type: spinbox
    min: 1
    max: 4096
    default: 1024
    description: Maximum number of isoforms per peptide.
  n_modifications_max:
    type: spinbox
    min: 1
    max: 10
    default: 3
    description: Limit the number of modifications per peptide.
  pseudo_reverse:
    type: checkbox
    default: true
    description: Use pseudo-reverse strategy instead of reverse.
  AL_swap:
    type: checkbox
    default: false
    description: Swap A and L for decoy generation.
  KR_swap:
    type: checkbox
    default: false
    description: Swap K and R (only if terminal) for decoy generation.
  protease:
    type: combobox
    value:
    - arg-c
    - asp-n
    - bnps-skatole
    - caspase 1
    - caspase 2
    - caspase 3
    - caspase 4
    - caspase 5
    - caspase 6
    - caspase 7
    - caspase 8
    - caspase 9
    - caspase 10
    - chymotrypsin high specificity
    - chymotrypsin low specificity
    - clostripain
    - cnbr
    - enterokinase
    - factor xa
    - formic acid
    - glutamyl endopeptidase
    - granzyme b
    - hydroxylamine
    - iodosobenzoic acid
    - lysc
    - ntcb
    - pepsin ph1.3
    - pepsin ph2.0
    - proline endopeptidase
    - proteinase k
    - staphylococcal peptidase i
    - thermolysin
    - thrombin
    - trypsin_full
    - trypsin_exception
    - non-specific
    - trypsin
    default: trypsin
    description: Protease for digestions.
  spectra_block:
    type: spinbox
    min: 1000
    max: 1000000
    default: 100000
    description: Maximum number of sequences to be collected before theoretical spectra
      are generated.
  fasta_block:
    type: spinbox
    min: 100
    max: 10000
    default: 1000
    description: Number of fasta entries to be processed in one block.
  save_db:
    type: checkbox
    default: true
    description: Save DB or create on the fly.
  fasta_size_max:
    type: spinbox
    min: 1
    max: 1000000
    default: 100
    description: Maximum size of FASTA (MB) when switching on-the-fly.
features:
  max_gap:
    type: spinbox
    min: 1
    max: 10
    default: 2
  centroid_tol:
    type: spinbox
    min: 1
    max: 25
    default: 8
  hill_length_min:
    type: spinbox
    min: 1
    max: 10
    default: 3
  hill_split_level:
    type: doublespinbox
    min: 0.1
    max: 10.0
    default: 1.3
  iso_split_level:
    type: doublespinbox
    min: 0.1
    max: 10.0
    default: 1.3
  hill_smoothing:
    type: spinbox
    min: 1
    max: 10
    default: 1
  hill_check_large:
    type: spinbox
    min: 1
    max: 100
    default: 40
  iso_charge_min:
    type: spinbox
    min: 1
    max: 6
    default: 1
  iso_charge_max:
    type: spinbox
    min: 1
    max: 6
    default: 6
  iso_n_seeds:
    type: spinbox
    min: 1
    max: 500
    default: 100
  hill_nboot_max:
    type: spinbox
    min: 1
    max: 500
    default: 300
  hill_nboot:
    type: spinbox
    min: 1
    max: 500
    default: 150
  iso_mass_range:
    type: spinbox
    min: 1
    max: 10
    default: 5
  iso_corr_min:
    type: doublespinbox
    min: 0.1
    max: 1
    default: 0.6
  map_mz_range:
    type: doublespinbox
    min: 0.1
    max: 2
    default: 1.5
  map_rt_range:
    type: doublespinbox
    min: 0.1
    max: 1
    default: 0.5
  map_mob_range:
    type: doublespinbox
    min: 0.1
    max: 1
    default: 0.3
  map_n_neighbors:
    type: spinbox
    min: 1
    max: 10
    default: 5
  search_unidentified:
    type: checkbox
    default: false
    description: Search MSMS w/o feature.
search:
  prec_tol:
    type: spinbox
    min: 1
    max: 500
    default: 30
    description: Maximum allowed precursor mass offset.
  frag_tol:
    type: spinbox
    min: 1
    max: 500
    default: 30
    description: Maximum fragment mass tolerance.
  min_frag_hits:
    type: spinbox
    min: 1
    max: 99
    default: 7
    description: Minimum number of fragment hits.
  ppm:
    type: checkbox
    default: true
    description: Use ppm instead of Dalton.
  calibrate:
    type: checkbox
    default: true
    description: Recalibrate masses.
  calibration_std_prec:
    type: spinbox
    min: 1
    max: 10
    default: 5
    description: Std range for precursor tolerance after calibration.
  calibration_std_frag:
    type: spinbox
    min: 1
    max: 10
    default: 5
    description: Std range for fragment tolerance after calibration.
  parallel:
    type: checkbox
    default: true
    description: Use parallel processing.
  peptide_fdr:
    type: doublespinbox
    min: 0.0
    max: 1.0
    default: 0.01
    description: FDR level for peptides.
  protein_fdr:
    type: doublespinbox
    min: 0.0
    max: 1.0
    default: 0.01
    description: FDR level for proteins.
  recalibration_min:
    type: spinbox
    min: 100
    max: 10000
    default: 100
    description: Minimum number of datapoints to perform calibration.
score:
  method:
    type: combobox
    value:
    - x_tandem
    - random_forest
    default: random_forest
    description: Scoring method.
calibration:
  outlier_std:
    type: spinbox
    min: 1
    max: 5
    default: 3
    description: Number of std. deviations to filter outliers in psms.
  calib_n_neighbors:
    type: spinbox
    min: 1
    max: 1000
    default: 100
    description: Number of neighbors that are used for offset interpolation.
  calib_mz_range:
    type: spinbox
    min: 1
    max: 1000
    default: 20
    description: Scaling factor for mz axis.
  calib_rt_range:
    type: doublespinbox
    min: 0.0
    max: 10
    default: 0.5
    description: Scaling factor for rt axis.
  calib_mob_range:
    type: doublespinbox
    min: 0.0
    max: 1.0
    default: 0.3
    description: Scaling factor for mobility axis.
matching:
  match_p_min:
    type: doublespinbox
    min: 0.001
    max: 1.0
    default: 0.05
    description: Minimum probability cutoff for matching.
  match_d_min:
    type: doublespinbox
    min: 0.001
    max: 10.0
    default: 3
    description: Minimum distance cutoff for matching.
  match_group_tol:
    type: spinbox
    min: 0
    max: 100
    default: 0
    description: When having matching groups, match neighboring groups.
isobaric_label:
  label:
    type: combobox
    value:
    - None
    - TMT10plex
    default: None
    description: Type of isobaric label present.
  reporter_frag_tolerance:
    type: spinbox
    min: 1
    max: 500
    default: 15
    description: Maximum fragment mass tolerance for a reporter.
  reporter_frag_tolerance_ppm:
    type: checkbox
    default: true
    description: Use ppm instead of Dalton.
quantification:
  max_lfq:
    type: checkbox
    default: true
    description: Perform max lfq type quantification.
  lfq_ratio_min:
    type: spinbox
    min: 1
    max: 10
    default: 1
    description: Minimum number of ratios for LFQ.
  mode:
    type: combobox
    value:
    - ms1_int_sum
    default: ms1_int_sum
    description: Column to perform quantification on.
